version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.prod
    container_name: comments_api
    volumes:
      - static_volume:/home/app/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.prod
    container_name: nginx
    volumes:
      - static_volume:/home/app/static
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
