version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    container_name: comments_api
    volumes:
      - ./app/:/usr/src/app/app/
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
